### ISSUE TITLE
支持支持，建议加2个编辑器: Slate.js 和 tui.editor

### ISSUE THREAD

**Issue by 1c7** [xjh22222228/awesome-web-editor#1]
支持支持~ 

## 看到 https://www.v2ex.com/t/474960#reply5 所以过来看了一眼。

(PS：我前几天才写了一篇内容类似的博客：http://1c7.me/2018-rich-text-wysiwyg-editor-full-list）
此 issue 可随时关闭

**Comment by xjh22222228** [comment]
thx!

**Comment by 1c7** [comment]
因为不想开新 issue 我继续留言。
Eleditor
https://github.com/Fixels/Eleditor
artEditor
https://github.com/baixuexiyang/artEditor

今天看到的，在列表里搜了一下还没有。感觉可以加进去。
